feat: LoginHeader component msw not working.. #50
42Box/front-end2.0 pull request #61
Opened 2023-08-22 14:22 UTC by tomatozil

테스트는 일단 집어치우고 마이페이지 버튼까지 해봄
- 지금은 깡통처럼 버튼만 누르면 로그인으로 간주됨.
- 응답 데이터를 잘 받아왔다고 판단되면 로그인으로 간주되도록 하고싶움.. 테스트 왜 안되는데;

- 마이페이지 연결 o
- 아이콘 게시판 연결 ㅇ

**중요** recoil 전역변수로 loinState를 따로 뒀습니다. 관리하기 더 쉬울듯하여

2023-08-22 15:46 UTC, Clearsu requested changes
msw로 테스트 하시느라 고생 많으셨습니다! 코멘트 남긴 부분 확인 부탁드립니다.

2023-08-22 15:46 UTC, Clearsu commented on public/index.html
파비콘이랑 로고랑 manifest 이거 지우신 이유가 궁금합니다!

2023-08-22 15:46 UTC, Clearsu commented on src/atom/userState.js
userState가 유저 상태정보를 담는 곳인데 로그인 상태인지 아닌지도 여기에 함께 담는 게 관리하기 더 편하지 않을까요?

2023-08-22 15:46 UTC, Clearsu commented on src/component/Main/RandingPage.jsx
CommonButton은 내부에 Link 컴포넌트만 가지고 있는데, 함수로 분리하지 않아도 괜찮을 것 같다는 생각이 드는데 어떠신가요?

2023-08-22 16:15 UTC, tomatozil commented on public/index.html
처음 실행할때 리액트 페이지 뜨잖아요? 거기 있는 이미지들(리액트 로고 등)가져오는 부분이라 저희에겐 필요없다고 판단했습니다.

2023-08-22 16:25 UTC, tomatozil commented on src/atom/userState.js
값을 가져올때 .isLoggedIn 을 꼭 붙여서 가져오는 것이 번거롭다고 생각했습니다. (실제로 코드가 더 길어짐) 로그인 상태만 확인하고 싶은데 객체를 다 들고올 필요가 있나? 싶었고요. 추후 로그인 상태에 따라 테마나 임티가 변하는 로직이 추가되고, userState에 다 넣눈게 오히려 덜 번거롭게 느껴진다면(코드를 줄일 수 있다면) 그때 재고해보지 않으시렵니까?

2023-08-22 16:27 UTC, tomatozil commented on src/component/Main/RandingPage.jsx
저 이거 싹 다 바꿨는데 왜 이전 버전이 올라갔는지 영문 x
내일 다시 올리겠습니다.

2023-08-22 16:28 UTC, tomatozil commented on src/component/Main/RandingPage.jsx
밑에 보시면 바꾼 버전이 있군요 두개가 올라갔나

2023-08-23 02:05 UTC, Clearsu commented on src/atom/userState.js
네 확인했습니다~

2023-08-23 02:05 UTC, Clearsu commented on src/component/Main/RandingPage.jsx
확인했습니다~~

2023-08-23 02:06 UTC, Clearsu approved these changes

2023-08-23 02:40 UTC, merged